# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The Oxford Spires
tagline:          'Inspiring Young Minds'
description:      ''
baseurl:          ''
url:              http://theoxfordspires.co.uk

author:
  name:           'Derek Feng'
  url:            http://whatwouldhartigan.com

paginate:         5

# Custom vars
version:          2.0.0